import Head from "next/head";

import { connectToAnki } from "./api/anki_connect/anki_connect";

import { type NextPage } from "next";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Practice Pal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Practice Pal
          </h1>
          <div>
            <button
              className="rounded-lg bg-indigo-300 p-5"
              onClick={connectToAnki}
            >
              Connect to Anki
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
